import { Roboto, Roboto_Mono } from "next/font/google";
import "@/styles/globals.css";
import "@/styles/Layout.sass";

const robotoSans = Roboto({
  variable: "--font-roboto-sans",
  weight: ["400"],
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${robotoSans.variable} ${robotoMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
